---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
generator:
  name: "NewSpringBootRestService"
  group: "atomist"
  artifact: "spring-rugs"
  version: "0.13.3"
  parameters:
    - "artifactId": "myartifact"
    - "groupId": "mygroup"
    - "version": "0.1.0-SNAPSHOT"
    - "description": "my new project"
    - "rootPackage": "com.myorg"
    - "serviceClassName": "Test"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddTravisWebhook"
  group: "atomist"
  artifact: "enrollment-rugs"
  version: "0.2.59"
  origin:
    repo: "git@github.com:atomisthq/enrollment-rugs"
    branch: "nortissej/suggest-build-integration"
    sha: "c8499cf*"

